### ISSUE TITLE
Question about stack

### ISSUE THREAD

**Issue by g3blv** [alexhuntley/Plots#28]
Please feel free to close.

Nice app!

I would like to create a similar app to print candle stick graphs. 

I just like to know what stack you are using.

To me it looks like you are using Python and GTK (3 or 4?).

How do you create plots in GTK? I have tried to find some library for graphs/plots in GTK but I haven't found any.

How do you find the general experience with Python and GTK?

What tools/IDE are using for development and creating the UI?

Thx!

**Comment by alexhuntley** [comment]
Hi, you can find the libraries in use at https://github.com/alexhuntley/Plots/network/dependencies.

I am indeed using Python 3 and GTK 3.

The plotting code is custom-built, using OpenGL 3.3 shaders.

But for your purposes, if you cannot find a plot drawing widget, it would most likely be easier to use Cairo (the software renderer used by GTK 3). It also has Python bindings, and I use it to draw the equation editor in Plots (inside a GTK DrawingArea).

I can't complain about the Python and GTK experience. Python is well-supported and there are plenty of libraries/bindings.

As for tools I am using Emacs for code and Glade for the UI. But Gnome Builder would have been a better idea (initially at least) because it has templates which can set up your project easily with the correct structure.

Hope this helps.
